

import type { Metadata } from "next";


import { JetBrains_Mono } from "next/font/google";
import "./globals.css";


import Header from "@/components/Header";
import PageTransitions from "@/components/PageTransitions";
import Stairs from "@/components/ui/Stairs";
import StairTransition from "@/components/ui/StairTransition";

const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: "--font-jetbrainsMono",

});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${JetBrainsMono.variable}  antialiased`}
      >
        <Header/>
        <StairTransition/>
        <PageTransitions>
          {children}

        </PageTransitions>
      </body>
    </html>
  );
}
